// Actions constants

const GET_USER_CREDENTIALS: 'GET_USER_CREDENTIALS' = 'GET_USER_CREDENTIALS';
const GET_USER_CREDENTIALS_SUCCESS: 'GET_USER_CREDENTIALS_SUCCESS' = 'GET_USER_CREDENTIALS_SUCCESS';
const GET_USER_CREDENTIALS_FAILURE: 'GET_USER_CREDENTIALS_FAILURE' = 'GET_USER_CREDENTIALS_FAILURE';
const USER_LOGOUT: 'USER_LOGOUT' = 'USER_LOGOUT';
const USER_RESET_FAILURE: 'USER_RESET_FAILURE' = 'USER_RESET_FAILURE';

export {
  GET_USER_CREDENTIALS,
  GET_USER_CREDENTIALS_SUCCESS,
  GET_USER_CREDENTIALS_FAILURE,
  USER_LOGOUT,
  USER_RESET_FAILURE,
};
